version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:16.0
    environment:
      NODE_OPTIONS: --max_old_space_size=16000
    resource_class: xlarge # specifies a machine with 8 vCPUs and 16GB of memory
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Build
          command: npm run docs:build
      - persist_to_workspace:
          root: .
          paths:
            - docs/.vitepress/dist
workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
